# ===============================
# APPLICATION
# ===============================
spring.application.name=demo

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=misminasyan@gmail.com
spring.mail.password=kkggngutkgzvvttv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ===============================
# JPA / HIBERNATE
# ===============================
# update
spring.jpa.hibernate.ddl-auto=update

#  SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGGING
# ===============================
# DDL (create / alter table)
logging.level.org.hibernate.tool.schema=DEBUG

# SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# SERVER
# ===============================
server.port=8080
